<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251126190000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Safe migration: create batiparti.appel and ensure utilisateur sequence/default';
    }

    public function up(Schema $schema): void
    {
        // Ensure the correct sequence exists for batiparti.utilisateur
        $this->addSql("CREATE SEQUENCE IF NOT EXISTS batiparti.utilisateur_noUtilisateur_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("SELECT setval('batiparti.utilisateur_noUtilisateur_seq', COALESCE((SELECT MAX(\"noUtilisateur\") FROM batiparti.utilisateur), 1), true)");
        $this->addSql("ALTER TABLE IF EXISTS batiparti.utilisateur ALTER COLUMN \"noUtilisateur\" SET DEFAULT nextval('batiparti.utilisateur_noUtilisateur_seq'::regclass)");

        // Create appel table only if it doesn't exist
        $this->addSql("CREATE TABLE IF NOT EXISTS batiparti.appel (noAppel INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, dateAppel DATE DEFAULT CURRENT_DATE NOT NULL, montantAppel NUMERIC(10, 2) DEFAULT NULL, dateReglAppel DATE DEFAULT NULL, noChantier INT DEFAULT NULL, PRIMARY KEY (noAppel))");
        $this->addSql("CREATE INDEX IF NOT EXISTS IDX_31DDD91550458809 ON batiparti.appel (noChantier)");

        // Add FK only if not already present and if referenced table exists
        $this->addSql(<<<'SQL'
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='batiparti' AND table_name='appel') AND
     EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='batiparti' AND table_name='chantier') THEN
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.table_constraints tc
      JOIN information_schema.key_column_usage kcu ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
      WHERE tc.constraint_type = 'FOREIGN KEY' AND tc.table_schema='batiparti' AND tc.table_name='appel' AND kcu.column_name='noChantier') THEN
      ALTER TABLE batiparti.appel ADD CONSTRAINT FK_31DDD91550458809 FOREIGN KEY (noChantier) REFERENCES batiparti.chantier (noChantier) ON DELETE CASCADE;
    END IF;
  END IF;
END
$$;
SQL
        );
    }

    public function down(Schema $schema): void
    {
        // Revert the changes: drop appel table and remove default on utilisateur
        $this->addSql("ALTER TABLE IF EXISTS batiparti.utilisateur ALTER COLUMN \"noUtilisateur\" DROP DEFAULT");
        $this->addSql("DROP TABLE IF EXISTS batiparti.appel CASCADE");
    }
}
