<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251126172501 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // Safe: only create missing tables and constraints in schema batiparti
        $this->addSql('CREATE TABLE IF NOT EXISTS batiparti.artisan (noArtisan INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nomArtisan VARCHAR(50) NOT NULL, prenomArtisan VARCHAR(50) DEFAULT NULL, adresseArtisan VARCHAR(100) DEFAULT NULL, cpArtisan VARCHAR(5) DEFAULT NULL, villeArtisan VARCHAR(50) DEFAULT NULL, PRIMARY KEY (noArtisan))');
        $this->addSql('CREATE TABLE IF NOT EXISTS batiparti.etre_qualifie_pour (noArtisan INT NOT NULL, noEtape INT NOT NULL, PRIMARY KEY (noArtisan, noEtape))');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_53E9BA8E15D210BE ON batiparti.etre_qualifie_pour (noArtisan)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_53E9BA8E90FBF88D ON batiparti.etre_qualifie_pour (noEtape)');
        $this->addSql('CREATE TABLE IF NOT EXISTS batiparti.chantier (noChantier INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, adresseChantier VARCHAR(100) DEFAULT NULL, cpChantier VARCHAR(5) DEFAULT NULL, villeChantier VARCHAR(50) DEFAULT NULL, dateCreation DATE NOT NULL, statutChantier VARCHAR(20) DEFAULT \'À compléter\' NOT NULL, noClient INT NOT NULL, noMOE INT DEFAULT NULL, noModele INT DEFAULT NULL, PRIMARY KEY (noChantier))');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_90505D51AC97F12C ON batiparti.chantier (noClient)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_90505D518A702122 ON batiparti.chantier (noMOE)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_90505D517BD17021 ON batiparti.chantier (noModele)');
        $this->addSql('CREATE TABLE IF NOT EXISTS batiparti.client (noClient INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nomClient VARCHAR(50) NOT NULL, prenomClient VARCHAR(50) NOT NULL, adresseClient VARCHAR(100) DEFAULT NULL, cpClient VARCHAR(5) DEFAULT NULL, villeClient VARCHAR(50) DEFAULT NULL, PRIMARY KEY (noClient))');
        $this->addSql('CREATE TABLE IF NOT EXISTS batiparti.commercial (noCommercial INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nomCommercial VARCHAR(50) NOT NULL, prenomCommercial VARCHAR(50) NOT NULL, noUtilisateur INT NOT NULL, PRIMARY KEY (noCommercial))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS UNIQ_27C5B29D51A03E9D ON batiparti.commercial (noUtilisateur)');
        $this->addSql('CREATE TABLE IF NOT EXISTS batiparti.construire (montantFacture NUMERIC(10, 2) DEFAULT NULL, coutSousTraitant NUMERIC(10, 2) DEFAULT NULL, nbJoursRealisation INT DEFAULT NULL, noModele INT NOT NULL, noEtape INT NOT NULL, PRIMARY KEY (noModele, noEtape))');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_3B6072A67BD17021 ON batiparti.construire (noModele)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_3B6072A690FBF88D ON batiparti.construire (noEtape)');
        $this->addSql('CREATE TABLE IF NOT EXISTS batiparti.etape (noEtape INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nomEtape VARCHAR(50) NOT NULL, reservable BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY (noEtape))');
        $this->addSql('CREATE TABLE IF NOT EXISTS batiparti.etape_chantier (noEtapeChantier INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, montantTheoriqueFacture NUMERIC(10, 2) DEFAULT NULL, reservee BOOLEAN DEFAULT false NOT NULL, reducSuppl NUMERIC(5, 2) DEFAULT NULL, descriptionReducSuppl VARCHAR(100) DEFAULT NULL, dateDebutTheorique DATE DEFAULT NULL, dateDebut DATE DEFAULT NULL, dateFin DATE DEFAULT NULL, statutEtape VARCHAR(20) DEFAULT \'À venir\' NOT NULL, noChantier INT DEFAULT NULL, noEtape INT DEFAULT NULL, PRIMARY KEY (noEtapeChantier))');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_DA84B94F50458809 ON batiparti.etape_chantier (noChantier)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_DA84B94F90FBF88D ON batiparti.etape_chantier (noEtape)');
        $this->addSql('CREATE TABLE IF NOT EXISTS batiparti.confier (noEtapeChantier INT NOT NULL, noArtisan INT NOT NULL, PRIMARY KEY (noEtapeChantier, noArtisan))');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_8153C535ABE56FDF ON batiparti.confier (noEtapeChantier)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_8153C53515D210BE ON batiparti.confier (noArtisan)');
        $this->addSql('CREATE TABLE IF NOT EXISTS batiparti.facture_artisan (noFacture INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, dateFacture DATE NOT NULL, montantFacture NUMERIC(10, 2) NOT NULL, nbJoursTravail INT DEFAULT NULL, dateReglFacture DATE DEFAULT NULL, noArtisan INT DEFAULT NULL, PRIMARY KEY (noFacture))');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_EB90FED315D210BE ON batiparti.facture_artisan (noArtisan)');
        $this->addSql('CREATE TABLE IF NOT EXISTS batiparti.associer (noFacture INT NOT NULL, noEtapeChantier INT NOT NULL, PRIMARY KEY (noFacture, noEtapeChantier))');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_91C771ED7347E7D ON batiparti.associer (noFacture)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_91C771EABE56FDF ON batiparti.associer (noEtapeChantier)');
        $this->addSql('CREATE TABLE IF NOT EXISTS batiparti.maitre_oeuvre (noMOE INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nomMOE VARCHAR(50) NOT NULL, prenomMOE VARCHAR(50) NOT NULL, noUtilisateur INT NOT NULL, PRIMARY KEY (noMOE))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS UNIQ_E0BB11B851A03E9D ON batiparti.maitre_oeuvre (noUtilisateur)');
        $this->addSql('CREATE TABLE IF NOT EXISTS batiparti.modele (noModele INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nomModele VARCHAR(50) NOT NULL, descriptionModele TEXT DEFAULT NULL, PRIMARY KEY (noModele))');

                // Foreign keys between batiparti tables (created conditionally)
                $this->addSql(<<<'SQL'
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints tc
        WHERE tc.constraint_schema='batiparti' AND tc.constraint_name='FK_53E9BA8E15D210BE') THEN
        ALTER TABLE batiparti.etre_qualifie_pour ADD CONSTRAINT FK_53E9BA8E15D210BE FOREIGN KEY (noArtisan) REFERENCES batiparti.artisan (noArtisan);
    END IF;
END
$$;
SQL
                );
                $this->addSql(<<<'SQL'
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints tc
        WHERE tc.constraint_schema='batiparti' AND tc.constraint_name='FK_53E9BA8E90FBF88D') THEN
        ALTER TABLE batiparti.etre_qualifie_pour ADD CONSTRAINT FK_53E9BA8E90FBF88D FOREIGN KEY (noEtape) REFERENCES batiparti.etape (noEtape);
    END IF;
END
$$;
SQL
                );
                $this->addSql(<<<'SQL'
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints tc
        WHERE tc.constraint_schema='batiparti' AND tc.constraint_name='FK_90505D51AC97F12C') THEN
        ALTER TABLE batiparti.chantier ADD CONSTRAINT FK_90505D51AC97F12C FOREIGN KEY (noClient) REFERENCES batiparti.client (noClient);
    END IF;
END
$$;
SQL
                );
                $this->addSql(<<<'SQL'
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints tc
        WHERE tc.constraint_schema='batiparti' AND tc.constraint_name='FK_90505D518A702122') THEN
        ALTER TABLE batiparti.chantier ADD CONSTRAINT FK_90505D518A702122 FOREIGN KEY (noMOE) REFERENCES batiparti.maitre_oeuvre (noMOE);
    END IF;
END
$$;
SQL
                );
                $this->addSql(<<<'SQL'
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints tc
        WHERE tc.constraint_schema='batiparti' AND tc.constraint_name='FK_90505D517BD17021') THEN
        ALTER TABLE batiparti.chantier ADD CONSTRAINT FK_90505D517BD17021 FOREIGN KEY (noModele) REFERENCES batiparti.modele (noModele);
    END IF;
END
$$;
SQL
                );
                $this->addSql(<<<'SQL'
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints tc
        WHERE tc.constraint_schema='batiparti' AND tc.constraint_name='FK_27C5B29D51A03E9D') THEN
        ALTER TABLE batiparti.commercial ADD CONSTRAINT FK_27C5B29D51A03E9D FOREIGN KEY (noUtilisateur) REFERENCES batiparti.utilisateur ("noUtilisateur");
    END IF;
END
$$;
SQL
                );
                $this->addSql(<<<'SQL'
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints tc
        WHERE tc.constraint_schema='batiparti' AND tc.constraint_name='FK_3B6072A67BD17021') THEN
        ALTER TABLE batiparti.construire ADD CONSTRAINT FK_3B6072A67BD17021 FOREIGN KEY (noModele) REFERENCES batiparti.modele (noModele);
    END IF;
END
$$; 
SQL
                );
                $this->addSql(<<<'SQL'
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints tc
        WHERE tc.constraint_schema='batiparti' AND tc.constraint_name='FK_3B6072A690FBF88D') THEN
        ALTER TABLE batiparti.construire ADD CONSTRAINT FK_3B6072A690FBF88D FOREIGN KEY (noEtape) REFERENCES batiparti.etape (noEtape);
    END IF;
END
$$;
SQL
                );
                $this->addSql(<<<'SQL'
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints tc
        WHERE tc.constraint_schema='batiparti' AND tc.constraint_name='FK_DA84B94F50458809') THEN
        ALTER TABLE batiparti.etape_chantier ADD CONSTRAINT FK_DA84B94F50458809 FOREIGN KEY (noChantier) REFERENCES batiparti.chantier (noChantier);
    END IF;
END
$$;
SQL
                );
                $this->addSql(<<<'SQL'
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints tc
        WHERE tc.constraint_schema='batiparti' AND tc.constraint_name='FK_DA84B94F90FBF88D') THEN
        ALTER TABLE batiparti.etape_chantier ADD CONSTRAINT FK_DA84B94F90FBF88D FOREIGN KEY (noEtape) REFERENCES batiparti.etape (noEtape);
    END IF;
END
$$;
SQL
                );
                $this->addSql(<<<'SQL'
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints tc
        WHERE tc.constraint_schema='batiparti' AND tc.constraint_name='FK_8153C535ABE56FDF') THEN
        ALTER TABLE batiparti.confier ADD CONSTRAINT FK_8153C535ABE56FDF FOREIGN KEY (noEtapeChantier) REFERENCES batiparti.etape_chantier (noEtapeChantier);
    END IF;
END
$$;
SQL
                );
                $this->addSql(<<<'SQL'
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints tc
        WHERE tc.constraint_schema='batiparti' AND tc.constraint_name='FK_8153C53515D210BE') THEN
        ALTER TABLE batiparti.confier ADD CONSTRAINT FK_8153C53515D210BE FOREIGN KEY (noArtisan) REFERENCES batiparti.artisan (noArtisan);
    END IF;
END
$$;
SQL
                );
                $this->addSql(<<<'SQL'
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints tc
        WHERE tc.constraint_schema='batiparti' AND tc.constraint_name='FK_EB90FED315D210BE') THEN
        ALTER TABLE batiparti.facture_artisan ADD CONSTRAINT FK_EB90FED315D210BE FOREIGN KEY (noArtisan) REFERENCES batiparti.artisan (noArtisan);
    END IF;
END
$$;
SQL
                );
                $this->addSql(<<<'SQL'
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints tc
        WHERE tc.constraint_schema='batiparti' AND tc.constraint_name='FK_91C771ED7347E7D') THEN
        ALTER TABLE batiparti.associer ADD CONSTRAINT FK_91C771ED7347E7D FOREIGN KEY (noFacture) REFERENCES batiparti.facture_artisan (noFacture);
    END IF;
END
$$;
SQL
                );
                $this->addSql(<<<'SQL'
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints tc
        WHERE tc.constraint_schema='batiparti' AND tc.constraint_name='FK_91C771EABE56FDF') THEN
        ALTER TABLE batiparti.associer ADD CONSTRAINT FK_91C771EABE56FDF FOREIGN KEY (noEtapeChantier) REFERENCES batiparti.etape_chantier (noEtapeChantier);
    END IF;
END
$$;
SQL
                );
                $this->addSql(<<<'SQL'
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints tc
        WHERE tc.constraint_schema='batiparti' AND tc.constraint_name='FK_E0BB11B851A03E9D') THEN
        ALTER TABLE batiparti.maitre_oeuvre ADD CONSTRAINT FK_E0BB11B851A03E9D FOREIGN KEY (noUtilisateur) REFERENCES batiparti.utilisateur ("noUtilisateur");
    END IF;
END
$$;
SQL
                );
    }

    public function down(Schema $schema): void
    {
        // Safe rollback: drop created batiparti tables (if needed)
        $this->addSql('ALTER TABLE IF EXISTS batiparti.confier DROP CONSTRAINT IF EXISTS FK_8153C535ABE56FDF');
        $this->addSql('ALTER TABLE IF EXISTS batiparti.confier DROP CONSTRAINT IF EXISTS FK_8153C53515D210BE');
        $this->addSql('ALTER TABLE IF EXISTS batiparti.associer DROP CONSTRAINT IF EXISTS FK_91C771ED7347E7D');
        $this->addSql('ALTER TABLE IF EXISTS batiparti.associer DROP CONSTRAINT IF EXISTS FK_91C771EABE56FDF');
        $this->addSql('ALTER TABLE IF EXISTS batiparti.facture_artisan DROP CONSTRAINT IF EXISTS FK_EB90FED315D210BE');
        $this->addSql('ALTER TABLE IF EXISTS batiparti.etre_qualifie_pour DROP CONSTRAINT IF EXISTS FK_53E9BA8E15D210BE');
        $this->addSql('ALTER TABLE IF EXISTS batiparti.etre_qualifie_pour DROP CONSTRAINT IF EXISTS FK_53E9BA8E90FBF88D');
        $this->addSql('ALTER TABLE IF EXISTS batiparti.etape_chantier DROP CONSTRAINT IF EXISTS FK_DA84B94F50458809');
        $this->addSql('ALTER TABLE IF EXISTS batiparti.etape_chantier DROP CONSTRAINT IF EXISTS FK_DA84B94F90FBF88D');
        $this->addSql('ALTER TABLE IF EXISTS batiparti.chantier DROP CONSTRAINT IF EXISTS FK_90505D51AC97F12C');
        $this->addSql('ALTER TABLE IF EXISTS batiparti.chantier DROP CONSTRAINT IF EXISTS FK_90505D518A702122');
        $this->addSql('ALTER TABLE IF EXISTS batiparti.chantier DROP CONSTRAINT IF EXISTS FK_90505D517BD17021');

        $this->addSql('DROP TABLE IF EXISTS batiparti.confier CASCADE');
        $this->addSql('DROP TABLE IF EXISTS batiparti.associer CASCADE');
        $this->addSql('DROP TABLE IF EXISTS batiparti.facture_artisan CASCADE');
        $this->addSql('DROP TABLE IF EXISTS batiparti.etre_qualifie_pour CASCADE');
        $this->addSql('DROP TABLE IF EXISTS batiparti.etape_chantier CASCADE');
        $this->addSql('DROP TABLE IF EXISTS batiparti.etape CASCADE');
        $this->addSql('DROP TABLE IF EXISTS batiparti.construire CASCADE');
        $this->addSql('DROP TABLE IF EXISTS batiparti.commercial CASCADE');
        $this->addSql('DROP TABLE IF EXISTS batiparti.client CASCADE');
        $this->addSql('DROP TABLE IF EXISTS batiparti.chantier CASCADE');
        $this->addSql('DROP TABLE IF EXISTS batiparti.artisan CASCADE');
        $this->addSql('DROP TABLE IF EXISTS batiparti.maitre_oeuvre CASCADE');
        $this->addSql('DROP TABLE IF EXISTS batiparti.modele CASCADE');
    }
}
