<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251127120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create batiparti.admin table similar to commercial';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE batiparti.admin ("noadmin" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "nomadmin" VARCHAR(50) NOT NULL, "prenomadmin" VARCHAR(50) NOT NULL, "noutilisateur" INT NOT NULL, PRIMARY KEY ("noadmin"))');
        $this->addSql('CREATE UNIQUE INDEX uniq_admin_noutilisateur ON batiparti.admin ("noutilisateur")');
        $this->addSql('ALTER TABLE batiparti.admin ADD CONSTRAINT fk_admin_noutilisateur FOREIGN KEY ("noutilisateur") REFERENCES batiparti.utilisateur ("noutilisateur") NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE IF EXISTS batiparti.admin DROP CONSTRAINT IF EXISTS fk_admin_noutilisateur');
        $this->addSql('DROP INDEX IF EXISTS batiparti.uniq_admin_noutilisateur');
        $this->addSql('DROP TABLE IF EXISTS batiparti.admin');
    }
}
